openapi: 3.0.1
info:
  title: Fetch App
  version: 1.0.0
  description: This is a API Specs for Fetch App made with Fiber and documented with Swagger
  contact:
    name: Fahrul Fauzi
    email: fahrul.fauz@gmail.com
servers:
  - url: http://localhost:4000
    description: Local
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
